- hosts: cvmfsproxy
  vars_files:
    - secret_group_vars/global.vault
    - group_vars/global.yml
    - group_vars/env.yml
    - group_vars/cvmfsproxy.yml
  become: true
  vars:

  handlers:

    - name: restart squid
      service:
        name: squid
        state: restarted
        enabled: yes

    - name: restart autofs
      service:
        name: autofs
        state: restarted
        enabled: yes

  tasks:

    - name: install packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - squid
        - firewalld
      tags:
        - server

    - name: enable and start services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - squid
        - firewalld
      tags:
        - server

    - name: opening firewall for public
      firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
        immediate: yes
        zone: public
      loop: "{{ public_ports }}"
      tags:
        - server

    - name: refresh squid cache
      command: /sbin/squid -z
      notify: restart squid
      changed_when: false
      tags:
        - server


    - name: opening firewall for proxy
      firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
        immediate: yes
        zone: internal
      loop: "{{ proxy_ports }}"
      tags:
        - server

    - name: add cvmfs clients to firewall
      firewalld:
        source: "{{ item }}"
        zone: internal
        state: enabled
        permanent: true
        immediate: yes
      loop: "{{ cvmfs_clients }}"
      tags:
        - server

    - name: copy squid.conf
      template:
        src: cvmfs/squid.conf.j2
        dest: /etc/squid/squid.conf
        owner: root
        group: squid
        mode: 0640
      notify: restart squid
      tags:
        - server

- hosts: galaxyserver
  gather_facts: yes
  become: true

  vars_files:
    - secret_group_vars/global.vault
    - group_vars/global.yml
    - group_vars/env.yml
    - group_vars/cvmfsproxy.yml

  handlers:

    - name: restart autofs
      service:
        name: autofs
        state: restarted

  tasks:

    - name: remove any old cvmfs proxy lines if exists
      lineinfile:
        path: /etc/cvmfs/default.local
        state: absent
        regexp: '^CVMFS_HTTP_PROXY'
        backup: yes
      tags:
        - change_clients

    - name: add proxy to cvmfs config
      lineinfile:
        path: /etc/cvmfs/default.local
        line: CVMFS_HTTP_PROXY="{{ cvmfs_proxy }}"
      notify:
        - restart autofs
      tags:
        - change_clients

- hosts: slurm
  gather_facts: yes
  become: true

  vars_files:
    - secret_group_vars/global.vault
    - group_vars/global.yml
    - group_vars/env.yml
    - group_vars/cvmfsproxy.yml

  handlers:

    - name: restart autofs
      service:
        name: autofs
        state: restarted

  tasks:

    - name: add pub key
      copy:
        src: cvmfs/data.galaxyproject.org.pub
        dest: /etc/cvmfs/keys/galaxyproject.org/data.galaxyproject.org.pub
        mode: '0644'
        owner: root
        group: root
      tags:
        - change_clients


    - name: remove any old cvmfs fstab lines if exists
      lineinfile:
        path: /etc/fstab
        state: absent
        regexp: '^{{ fstab_pattern }}'
        backup: yes
      tags:
        - change_clients

    - name: remove any old cvmfs proxy lines if exists
      lineinfile:
        path: /etc/cvmfs/default.local
        state: absent
        regexp: '^CVMFS_HTTP_PROXY'
        backup: yes
      tags:
        - change_clients


    - name: add proxy to cvmfs config
      lineinfile:
        path: /etc/cvmfs/default.local
        line: CVMFS_HTTP_PROXY="{{ cvmfs_proxy }}"
      notify:
        - restart autofs
      tags:
        - change_clients

    - name: umount nfs cvmfs
      mount:
        path: '{{ item }}'
        state: unmounted
      with_items:
        - "/cvmfs/data.galaxyproject.org"
        - "/cvmfs/data.usegalaxy.no"
      tags:
        - change_clients

    - name: enable autofs
      service:
        name: autofs
        state: started
        enabled: true
      tags:
        - change_clients