- hosts: database
  become: true
  tags:
    - database

  vars_files:
    - group_vars/global.yml
    - group_vars/database.yml
    - group_vars/certbot.yml
    - group_vars/rabbitmq.yml
    - group_vars/rabbitmq_proxy.yml

  vars:



  handlers:
    - name: restart rabbitmq
      service: name=rabbitmq-server state=restarted

  pre_tasks:
    - name: Install Dependencies
      package:
        name: ['epel-release', 'python3']
    - name: Install apache dependencies
      package:
        name: ['libproxy', 'mod_proxy_uwsgi']

  tasks:
    - name: Setup ssh access
      become: false
      include: tasks/keys.yml

    - name: setup rabbitmq vhosts and users
      include: tasks/rabbitmq.yml

  roles:
    - role: geerlingguy.postgresql
      become: yes
    - role: geerlingguy.certbot
    - role: geerlingguy.rabbitmq
    - geerlingguy.apache



