- hosts: database
  become: true
  tags:
    - database

  vars_files:
    - secret_group_vars/global.vault
    - group_vars/global.yml
    - group_vars/env.yml
    - group_vars/telegraf.yml
#    - group_vars/certbot.yml
    - group_vars/database.yml
    - group_vars/rabbitmq.yml
    - group_vars/rabbitmq_proxy.yml

  handlers:
    - name: restart rabbitmq
      service: name=rabbitmq-server state=restarted

  pre_tasks:
    - name: Install Dependencies
      package:
        name: ['python3', 'python-psycopg2']

    - name: Open firewalld ports
      tags: firewall-setup
      become: true
      include: tasks/firewall.yml ports="['ssh', 'http', 'https', 'amqp', 'amqps']"


  tasks:
    - name: Create users and groups
      include: tasks/users_groups.yml

    - name: setup rabbitmq certs, vhosts and users
      include: tasks/rabbitmq.yml
      tags:
        - rabbitmq



  roles:
    - geerlingguy.repo-epel
    - galaxyproject.postgresql
    - role: natefoo.postgresql_objects
      become: true
      become_user: postgres
    - role: geerlingguy.certbot
      tags:
        - certbot
    - geerlingguy.apache
    - role: geerlingguy.mysql
      tags:
      - mysql
    - role: dj-wasabi.telegraf
      tags:
        - telegraf
    - role: idiv-biodiversity.postfix
      tags:
        - postfix
