- hosts: database
  become: true
  tags:
    - database

  vars_files:
    - secret_group_vars/global.vault
    - group_vars/global.yml
    - group_vars/database.yml
    - group_vars/certbot.yml
    - group_vars/rabbitmq.yml
    - group_vars/rabbitmq_proxy.yml

  handlers:
    - name: restart rabbitmq
      service: name=rabbitmq-server state=restarted

  pre_tasks:
    - name: Install Dependencies
      package:
        name: ['python3', 'python-psycopg2']
  tasks:
    - name: Create users and groups
      include: tasks/users_groups.yml
    - name: setup rabbitmq certs, vhosts and users
      include: tasks/rabbitmq.yml
    - name: Create backup directory
      file:
        path: "{{ postgresql_backup_dir }}"
        state: directory
        mode: "0700"
        owner: "postgres"

  roles:
    - geerlingguy.repo-epel
    - galaxyproject.postgresql
    - role: natefoo.postgresql_objects
      become: true
      become_user: postgres
    - galaxyproject.nginx
    - geerlingguy.rabbitmq