- hosts: galaxyserver
  become: true
  tags:
    - galaxyserver
  vars_files:
    - secret_group_vars/global.vault
    - group_vars/global.yml
    - group_vars/galaxy.yml
    - group_vars/pulsar_nmbu_orion.yml
    - group_vars/slurm.yml
    - group_vars/telegraf.yml

  pre_tasks:
    - name: Install Dependencies
      package:
#        use_backend: dnf
        name:
          - 'python3'
          - 'python3-psycopg2'
          - 'git'
          - 'python36-virtualenv'
          - 'make'
          - 'bzip2'
          - 'postgresql'
    - name: Create users and groups
      include: tasks/users_groups.yml

  tasks:
    - name: Perform misc tasks
      include: tasks/galaxy.yml

  handlers:
    - name: Restart Galaxy
      systemd:
        name: galaxy
        state: restarted

  roles:
    - geerlingguy.repo-epel
    - geerlingguy.pip
    - galaxyproject.repos
    - galaxyproject.galaxy
    - role: uchida.miniconda
      become: true
      become_user: galaxy
    - usegalaxy_eu.galaxy_systemd
    - galaxyproject.nginx
    - galaxyproject.cvmfs
    - galaxyproject.repos
    - galaxyproject.slurm
    - role: dj-wasabi.telegraf
      tags:
        - telegraf
    - usegalaxy_eu.gie_proxy
    - usegalaxy_eu.gxadmin
    - role: usegalaxy-no.nels_storage
      tags:
        - nels

  post_tasks:
    - name: Install slurm-drmaa
      package:
        name: slurm-drmaa
    - name: Install the tos-api
      include_role:
        name: tos-api
    # TODO: This should not be needed, but...
    - name: galaxy need a compliance log for conda, will otherwise fail.
      file:
        path: "{{ galaxy_root }}/server/compliance.log"
        state: file
        mode: '0644'
        owner: "{{ galaxy_user.name }}"
    - name: galaxy root is readable for nginx
      file:
        path: "{{ galaxy_root }}"
        state: directory
        mode: '0755'
        owner: "{{ galaxy_user.name }}"
        group: "{{ galaxy_user.name }}"
    - name: Make sure galaxy owns tool-data
      file:
        path: "{{ galaxy_root }}/server/tool-data"
        state: directory
        recurse: yes
        mode: '0755'
        owner: "{{ galaxy_user.name }}"
    - name: Make sure galaxy owns /sanitize_whitelist.txt
      file:
        path: "{{ galaxy_mutable_config_dir }}/sanitize_whitelist.txt"
        state: file
        mode: '0755'
        owner: "{{ galaxy_user.name }}"
