---
- hosts: jenkins
  become: true
  pre_tasks:
    - name: Allow jenkins user to execute things as root
      copy:
        content: |
          jenkins ALL=(ALL:ALL) NOPASSWD:ALL
        dest: /etc/sudoers.d/jenkins
        validate: 'visudo -cf %s'
        mode: 0440
  roles:
    - geerlingguy.java
    - geerlingguy.jenkins
    - geerlingguy.ansible