- hosts: galaxyserver
  vars_files:
    - secret_group_vars/global.vault
    - group_vars/global.yml
    - group_vars/env.yml
    - group_vars/nga.yml
  become: true
  vars:
  roles:
    - name: usegalaxy-no.nels-galaxy-api
      source: https://github.com/usegalaxy-no/ansible-role-nels-galaxy-api.git
      version: reduced_functionality
