# Roles not from the Galaxy community
- src: geerlingguy.certbot
  version: 3.1.0
- src: geerlingguy.apache
  version: 3.1.0
- src: geerlingguy.ansible
  version: 2.0.2
- src: geerlingguy.docker
  version: 2.7.0
#  version: 6.1.0
- src: geerlingguy.git
  version: 3.0.0
- src: geerlingguy.java
  version: 1.10.0
- src: geerlingguy.jenkins
  version: 4.3.0
- src: geerlingguy.pip
  version: 1.3.0
- src: geerlingguy.supervisor
  version: 3.1.1
- src: geerlingguy.repo-epel
#  version: 1.3.0
- src: geerlingguy.mysql
  version: 3.1.0
- src: geerlingguy.nfs
  version: 1.5.0
- src: geerlingguy.rabbitmq
  version: 1.0.0
- src: weareinteractive.sudo
  version: 1.14.1

- src: https://github.com/dj-wasabi/ansible-telegraf
  name: dj-wasabi.telegraf
  #  version: 0.12.0
#- src: idiv-biodiversity.postfix
#  version: v0.4.0
#- src: indigo-dc.nfs
- src: nbigot.ansible-fail2ban
  version: v5.0.0
- src: reallyenglish.dhclient
  version: 1.0.0
- src: uchida.miniconda
  version: 0.3.0

# Roles from the Galaxy community
- src: galaxyproject.postgresql
  version: 1.0.2
- src: natefoo.postgresql_objects
  version: 1.1
- src: galaxyproject.galaxy
#  version: 0.9.6
#  version: 0.10.5 # used for v22.01 and v22.05
  version: 0.10.15 # used for v23.0
- src: https://github.com/usegalaxy-eu/ansible-role-supervisor
  name: usegalaxy-eu.supervisor
- src: https://github.com/galaxyproject/ansible-galaxy-tools.git
  name: usegalaxy.galaxy-tools
- src: galaxyproject.cvmfs
#  version: 0.2.13
  version: 0.2.21
- src: galaxyproject.repos
  version: 0.0.1
- src: galaxyproject.slurm
  version: 0.1.2
- src: usegalaxy_eu.galaxy_systemd
  version: 0.1.2
- src: galaxyproject.nginx
  version: 0.7.1
- src: usegalaxy_eu.certbot
  version: 0.1.11
- src: galaxyproject.pulsar
#- src: usegalaxy_eu.gxadmin
#  version: 0.0.5
- src: usegalaxy_eu.gie_proxy
  version: 0.0.1
- src: galaxyproject.tusd
  version: 0.0.1
# Celery, Redis, and Flower (dashboard)
- name: geerlingguy.redis
  version: 1.8.0
- name: usegalaxy_eu.flower
  version: 1.0.2

# usegalaxy roles
- src: https://github.com/usegalaxy-no/ansible-nels_storage
  name: usegalaxy-no.nels_storage
- src: https://github.com/elixir-no-nels/ansible-role-ehos.git
  name: usegalaxy-no.ehos
- src: https://github.com/usegalaxy-no/ansible-role-tos-api.git
  name: usegalaxy-no.tos-api
- src: https://github.com/usegalaxy-no/ansible-role-galaxy-tools.git
  name: usegalaxy-no.galaxy-tools
- src: https://github.com/usegalaxy-no/ansible-role-nels-galaxy-api.git
  name: usegalaxy-no.nels-galaxy-api
- src: https://github.com/usegalaxy-no/ansible-role-ecc
  name: usegalaxy-no.ecc
- src: https://github.com/usegalaxy-no/ansible-role-cvmfs-proxy
  name: usegalaxy-no.cvmfsproxy

# new additions by kjetil for v22.01
- src: galaxyproject.miniconda
  version: 0.3.1