# base system
- geerlingguy.postgresql
- geerlingguy.certbot
- geerlingguy.apache
  #- geerlingguy.nginx
- dj-wasabi.telegraf
  #- nginxinc.nginx

# Galaxy specefic stuff.
- galaxyproject.galaxy
- uchida.miniconda
- src: https://github.com/usegalaxy-eu/ansible-role-supervisor
  name: usegalaxy-eu.supervisor
- src: geerlingguy.pip
  version: 1.0.0
- src: https://github.com/galaxyproject/ansible-galaxy-tools.git
  name: usegalaxy.galaxy-tools
- galaxyproject.cvmfs
- src: galaxyproject.repos
  version: 0.0.1
- src: galaxyproject.slurm
  version: 0.1.2
- geerlingguy.rabbitmq
- usegalaxy_eu.galaxy_systemd
- galaxyproject.nginx
- usegalaxy_eu.certbot

