- hosts: galaxyserver, slurm
  become: true
  vars_files:
    - secret_group_vars/global.vault
    - group_vars/global.yml
    - group_vars/galaxy.yml
  tasks:
    - name: Create users and groups
      include: tasks/users_groups.yml
    - name: Galaxy related tasks
      include: tasks/slurm.yml

- hosts: galaxyserver
  become: true
  vars_files:
    - secret_group_vars/global.vault
    - group_vars/global.yml
    - group_vars/slurm.yml
    - group_vars/galaxy.yml
  vars:
    slurm_roles: ['controller', 'dbd']
    nfs_mode: server
  pre_tasks:
  - name: Add galaxy paths for nfs export
    become: true
    file:
      path: "{{ item }}"
      state: directory
      mode: '0750'
      owner: "{{ galaxy_user.name }}"
      group: "{{ galaxy_user.name }}"
    with_items:
      - "{{ galaxy_file_path }}"
      - "{{ galaxy_root }}"

  - name: Open firewalld ports
    tags: firewall-setup
    become: true
    include: tasks/firewall.yml ports="['ssh']"

  roles:
    - galaxyproject.repos
    - galaxyproject.slurm
    - indigo-dc.nfs
  post_tasks:
    - name: Install slurm-drmaa
      package:
        name: slurm-drmaa
    
- hosts: slurm
  become: true
  vars_files:
    - group_vars/global.yml
    - group_vars/slurm.yml
    - group_vars/galaxy.yml
  vars:
    slurm_roles: ['exec']
    nfs_mode: client

  pre_tasks:
    - name: Open firewalld ports
      tags: firewall-setup
      become: true
      include: tasks/firewall.yml ports="['ssh']"

  roles:
    - geerlingguy.repo-epel
    - galaxyproject.repos
    - galaxyproject.slurm
    - role: galaxyproject.cvmfs
      tags: cvmfs
    - geerlingguy.docker
    - indigo-dc.nfs
  post_tasks:
    - name: Install packages
      package:
        name:
          - 'slurm-drmaa'
          - 'python3'
          - 'git'
          - 'python36-virtualenv'
          - 'bzip2'
