#cloud-config

# Run yum upgrade
#package_upgrade: true

groups:
  - docker


runcmd:
  ## for Extra Packages for Enterprise Linux packages (stupid centos)
  - yum install -y epel-release 

  - yum -y groupinstall "development tools"

  ## some editors and tools we need
  - yum install -y vim   wget python36 python36-pip python36-devel libarchive-devel yum-utils openssl-devel

  # docker install 
  #- yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  #- yum install -y docker-ce

  ## Enable condor to run docker
  #- usermod -aG docker condor

  ## Enable rootless use of docker
  #- usermod -aG docker centos

  # htcondor install
  #- wget -P /etc/yum.repos.d https://research.cs.wisc.edu/htcondor/yum/repo.d/htcondor-stable-rhel7.repo
  - wget -P /etc/yum.repos.d https://research.cs.wisc.edu/htcondor/yum/repo.d/htcondor-previous-rhel7.repo

  - wget -P /tmp/ http://research.cs.wisc.edu/htcondor/yum/RPM-GPG-KEY-HTCondor
  - rpm --import /tmp/RPM-GPG-KEY-HTCondor
  - yum -y install condor.x86_64

  ## Enable condor to run docker
  #- usermod -aG docker condor

  # startup services

  ## Start docker and enable automatic start at boot
  #  - service docker start
  #  - systemctl enable docker

  # Start condor and enable it on start
  - service condor start
  - systemctl enable condor
  
final_message: "The EHOS vm is up after $UPTIME seconds"
