---
- name: ensure a list of packages installed
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - gcc
    - openssl-devel
    - bzip2-devel
    - libffi-devel
    - zlib-devel 
    - xz-devel
    - sqlite-devel 
    - ncurses-devel
  become: yes