id: nels_export_history
type:
  - history-menu
activate: true
title: Export History

function: >
  action="export";
  galaxy_url=window.location.protocol+"//"+window.location.host + Galaxy.root +"nga/history/export/request/";
  console.log(galaxy_url);
  window.location.href = galaxy_url

