
# Install the latest version of Telegraf
telegraf_agent_package_state: latest
ansible_os_family: RedHat

telegraf_agent_hostname: "{{ inventory_hostname }}"
telegraf_agent_interval: "60" # seconds

telegraf_agent_output:
  - type: "{{ telegraf.MAAS.type }}"
    config:
      - urls = {{ telegraf.MAAS.urls }}
      - database = "{{ telegraf.MAAS.database }}"
      - username = "{{ telegraf.MAAS.username }}"
      - password = "{{ telegraf.MAAS.password }}"
  - type: "{{ telegraf.si_elixir_no_prod.type }}"
    config:
      - urls = {{ telegraf.si_elixir_no_prod.urls }}
      - bucket = "{{ telegraf.si_elixir_no_prod.bucket }}"
      - organization = "{{ telegraf.si_elixir_no_prod.organization }}"
      - token = "{{ telegraf.si_elixir_no_prod.token }}"

#example config, needs to be determined later on
telegraf_plugins_default:
  - plugin: cpu
    config:
      - percpu = false
  - plugin: disk
  - plugin: kernel
  - plugin: processes
  - plugin: io
  - plugin: mem
  - plugin: system
  - plugin: swap
  - plugin: net
  - plugin: netstat
  - plugin: chrony
  - plugin: fail2ban
    config:
      - use_sudo = true
